services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=userdb'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'JWT_SECRET: ${JWT_SECRET}'
      - 'JWT_ISSUER: ${JWT_ISSUER'
    ports:
      - '5432:5432'

    env_file:
      - .env